// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: audit_config.sql

package pgmodel

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAuditConfig = `-- name: GetAuditConfig :one
SELECT app_id, guild_id, enabled, created_at, updated_at FROM audit.config WHERE app_id = $1 AND guild_id = $2
`

type GetAuditConfigParams struct {
	AppID   int64
	GuildID int64
}

func (q *Queries) GetAuditConfig(ctx context.Context, arg GetAuditConfigParams) (AuditConfig, error) {
	row := q.db.QueryRow(ctx, getAuditConfig, arg.AppID, arg.GuildID)
	var i AuditConfig
	err := row.Scan(
		&i.AppID,
		&i.GuildID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAuditConfig = `-- name: UpsertAuditConfig :exec
INSERT INTO audit.config (app_id, guild_id, enabled, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (app_id, guild_id)
DO UPDATE SET enabled = $3, updated_at = $5
`

type UpsertAuditConfigParams struct {
	AppID     int64
	GuildID   int64
	Enabled   bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

func (q *Queries) UpsertAuditConfig(ctx context.Context, arg UpsertAuditConfigParams) error {
	_, err := q.db.Exec(ctx, upsertAuditConfig,
		arg.AppID,
		arg.GuildID,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
