// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: entity_states.sql

package pgmodel

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEntityState = `-- name: GetEntityState :one
SELECT app_id, guild_id, entity_type, entity_id, data, deleted, created_at, updated_at FROM audit.entity_states WHERE app_id = $1 AND guild_id = $2 AND entity_type = $3 AND entity_id = $4
`

type GetEntityStateParams struct {
	AppID      int64
	GuildID    int64
	EntityType string
	EntityID   int64
}

func (q *Queries) GetEntityState(ctx context.Context, arg GetEntityStateParams) (AuditEntityState, error) {
	row := q.db.QueryRow(ctx, getEntityState,
		arg.AppID,
		arg.GuildID,
		arg.EntityType,
		arg.EntityID,
	)
	var i AuditEntityState
	err := row.Scan(
		&i.AppID,
		&i.GuildID,
		&i.EntityType,
		&i.EntityID,
		&i.Data,
		&i.Deleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertEntityState = `-- name: UpsertEntityState :exec
INSERT INTO audit.entity_states (app_id, guild_id, entity_type, entity_id, data, deleted, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (app_id, guild_id, entity_type, entity_id) DO UPDATE SET
    data = $5,
    deleted = $6,
    updated_at = $8
`

type UpsertEntityStateParams struct {
	AppID      int64
	GuildID    int64
	EntityType string
	EntityID   int64
	Data       []byte
	Deleted    bool
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

func (q *Queries) UpsertEntityState(ctx context.Context, arg UpsertEntityStateParams) error {
	_, err := q.db.Exec(ctx, upsertEntityState,
		arg.AppID,
		arg.GuildID,
		arg.EntityType,
		arg.EntityID,
		arg.Data,
		arg.Deleted,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
