// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package pgmodel

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEntityState struct {
	AppID      int64
	GuildID    int64
	EntityType string
	EntityID   int64
	Data       []byte
	Deleted    bool
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}
