// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: emojis.sql

package pgmodel

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteEmoji = `-- name: DeleteEmoji :exec
DELETE FROM cache.emojis WHERE app_id = $1 AND guild_id = $2 AND emoji_id = $3
`

type DeleteEmojiParams struct {
	AppID   int64
	GuildID int64
	EmojiID int64
}

func (q *Queries) DeleteEmoji(ctx context.Context, arg DeleteEmojiParams) error {
	_, err := q.db.Exec(ctx, deleteEmoji, arg.AppID, arg.GuildID, arg.EmojiID)
	return err
}

const getEmoji = `-- name: GetEmoji :one
SELECT app_id, guild_id, emoji_id, data, tainted, created_at, updated_at FROM cache.emojis WHERE app_id = $1 AND guild_id = $2 AND emoji_id = $3 LIMIT 1
`

type GetEmojiParams struct {
	AppID   int64
	GuildID int64
	EmojiID int64
}

func (q *Queries) GetEmoji(ctx context.Context, arg GetEmojiParams) (CacheEmoji, error) {
	row := q.db.QueryRow(ctx, getEmoji, arg.AppID, arg.GuildID, arg.EmojiID)
	var i CacheEmoji
	err := row.Scan(
		&i.AppID,
		&i.GuildID,
		&i.EmojiID,
		&i.Data,
		&i.Tainted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmojis = `-- name: GetEmojis :many
SELECT app_id, guild_id, emoji_id, data, tainted, created_at, updated_at FROM cache.emojis WHERE app_id = $1 AND guild_id = $2 ORDER BY emoji_id LIMIT $4 OFFSET $3
`

type GetEmojisParams struct {
	AppID   int64
	GuildID int64
	Offset  pgtype.Int4
	Limit   pgtype.Int4
}

func (q *Queries) GetEmojis(ctx context.Context, arg GetEmojisParams) ([]CacheEmoji, error) {
	rows, err := q.db.Query(ctx, getEmojis,
		arg.AppID,
		arg.GuildID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CacheEmoji
	for rows.Next() {
		var i CacheEmoji
		if err := rows.Scan(
			&i.AppID,
			&i.GuildID,
			&i.EmojiID,
			&i.Data,
			&i.Tainted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markShardEmojisTainted = `-- name: MarkShardEmojisTainted :exec
UPDATE cache.emojis SET tainted = TRUE WHERE app_id = $1 AND guild_id % $2 = $3
`

type MarkShardEmojisTaintedParams struct {
	AppID      int64
	ShardCount int64
	ShardID    int64
}

func (q *Queries) MarkShardEmojisTainted(ctx context.Context, arg MarkShardEmojisTaintedParams) error {
	_, err := q.db.Exec(ctx, markShardEmojisTainted, arg.AppID, arg.ShardCount, arg.ShardID)
	return err
}

const searchEmojis = `-- name: SearchEmojis :many
SELECT app_id, guild_id, emoji_id, data, tainted, created_at, updated_at FROM cache.emojis WHERE app_id = $1 AND guild_id = $2 AND data @> $3 ORDER BY emoji_id LIMIT $5 OFFSET $4
`

type SearchEmojisParams struct {
	AppID   int64
	GuildID int64
	Data    []byte
	Offset  pgtype.Int4
	Limit   pgtype.Int4
}

func (q *Queries) SearchEmojis(ctx context.Context, arg SearchEmojisParams) ([]CacheEmoji, error) {
	rows, err := q.db.Query(ctx, searchEmojis,
		arg.AppID,
		arg.GuildID,
		arg.Data,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CacheEmoji
	for rows.Next() {
		var i CacheEmoji
		if err := rows.Scan(
			&i.AppID,
			&i.GuildID,
			&i.EmojiID,
			&i.Data,
			&i.Tainted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
