// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: guilds.sql

package pgmodel

import (
	"context"
)

const deleteGuild = `-- name: DeleteGuild :exec
DELETE FROM cache.guilds WHERE app_id = $1 AND guild_id = $2
`

type DeleteGuildParams struct {
	AppID   int64
	GuildID int64
}

func (q *Queries) DeleteGuild(ctx context.Context, arg DeleteGuildParams) error {
	_, err := q.db.Exec(ctx, deleteGuild, arg.AppID, arg.GuildID)
	return err
}

const getGuild = `-- name: GetGuild :one
SELECT app_id, guild_id, data, unavailable, tainted, created_at, updated_at FROM cache.guilds WHERE app_id = $1 AND guild_id = $2 LIMIT 1
`

type GetGuildParams struct {
	AppID   int64
	GuildID int64
}

func (q *Queries) GetGuild(ctx context.Context, arg GetGuildParams) (CacheGuild, error) {
	row := q.db.QueryRow(ctx, getGuild, arg.AppID, arg.GuildID)
	var i CacheGuild
	err := row.Scan(
		&i.AppID,
		&i.GuildID,
		&i.Data,
		&i.Unavailable,
		&i.Tainted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markGuildUnavailable = `-- name: MarkGuildUnavailable :exec
UPDATE cache.guilds SET unavailable = TRUE WHERE app_id = $1 AND guild_id = $2
`

type MarkGuildUnavailableParams struct {
	AppID   int64
	GuildID int64
}

func (q *Queries) MarkGuildUnavailable(ctx context.Context, arg MarkGuildUnavailableParams) error {
	_, err := q.db.Exec(ctx, markGuildUnavailable, arg.AppID, arg.GuildID)
	return err
}

const markShardGuildsTainted = `-- name: MarkShardGuildsTainted :exec
UPDATE cache.guilds SET tainted = TRUE WHERE app_id = $1 AND guild_id % $2 = $3
`

type MarkShardGuildsTaintedParams struct {
	AppID      int64
	ShardCount int64
	ShardID    int64
}

func (q *Queries) MarkShardGuildsTainted(ctx context.Context, arg MarkShardGuildsTaintedParams) error {
	_, err := q.db.Exec(ctx, markShardGuildsTainted, arg.AppID, arg.ShardCount, arg.ShardID)
	return err
}
