// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: guilds.sql

package pgmodel

import (
	"context"
)

const deleteGuild = `-- name: DeleteGuild :exec
DELETE FROM cache.guilds WHERE group_id = $1 AND client_id = $2 AND guild_id = $3
`

type DeleteGuildParams struct {
	GroupID  string
	ClientID int64
	GuildID  int64
}

func (q *Queries) DeleteGuild(ctx context.Context, arg DeleteGuildParams) error {
	_, err := q.db.Exec(ctx, deleteGuild, arg.GroupID, arg.ClientID, arg.GuildID)
	return err
}

const getGuild = `-- name: GetGuild :one
SELECT group_id, client_id, guild_id, data, unavailable, tainted, created_at, updated_at FROM cache.guilds WHERE group_id = $1 AND client_id = $2 AND guild_id = $3 LIMIT 1
`

type GetGuildParams struct {
	GroupID  string
	ClientID int64
	GuildID  int64
}

func (q *Queries) GetGuild(ctx context.Context, arg GetGuildParams) (CacheGuild, error) {
	row := q.db.QueryRow(ctx, getGuild, arg.GroupID, arg.ClientID, arg.GuildID)
	var i CacheGuild
	err := row.Scan(
		&i.GroupID,
		&i.ClientID,
		&i.GuildID,
		&i.Data,
		&i.Unavailable,
		&i.Tainted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markGuildUnavailable = `-- name: MarkGuildUnavailable :exec
UPDATE cache.guilds SET unavailable = TRUE WHERE group_id = $1 AND client_id = $2 AND guild_id = $3
`

type MarkGuildUnavailableParams struct {
	GroupID  string
	ClientID int64
	GuildID  int64
}

func (q *Queries) MarkGuildUnavailable(ctx context.Context, arg MarkGuildUnavailableParams) error {
	_, err := q.db.Exec(ctx, markGuildUnavailable, arg.GroupID, arg.ClientID, arg.GuildID)
	return err
}

const markShardGuildsTainted = `-- name: MarkShardGuildsTainted :exec
UPDATE cache.guilds SET tainted = TRUE WHERE group_id = $1 AND client_id = $2 AND guild_id % $3 = $4
`

type MarkShardGuildsTaintedParams struct {
	GroupID    string
	ClientID   int64
	ShardCount int64
	ShardID    int64
}

func (q *Queries) MarkShardGuildsTainted(ctx context.Context, arg MarkShardGuildsTaintedParams) error {
	_, err := q.db.Exec(ctx, markShardGuildsTainted,
		arg.GroupID,
		arg.ClientID,
		arg.ShardCount,
		arg.ShardID,
	)
	return err
}
