// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: guilds.sql

package pgmodel

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertGuild = `-- name: UpsertGuild :exec
INSERT INTO cache.guilds (
    id, 
    app_id, 
    data, 
    created_at, 
    updated_at
) VALUES ($1, $2, $3, $4, $5) 
ON CONFLICT (id, app_id) DO UPDATE SET 
    data = EXCLUDED.data, 
    updated_at = EXCLUDED.updated_at
`

type UpsertGuildParams struct {
	ID        int64
	AppID     int64
	Data      []byte
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

func (q *Queries) UpsertGuild(ctx context.Context, arg UpsertGuildParams) error {
	_, err := q.db.Exec(ctx, upsertGuild,
		arg.ID,
		arg.AppID,
		arg.Data,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
