// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package pgmodel

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CacheGuild struct {
	ID        int64
	AppID     int64
	Data      []byte
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
