// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package pgmodel

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CacheChannel struct {
	AppID     int64
	GuildID   int64
	ChannelID int64
	Data      []byte
	Tainted   bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type CacheEmoji struct {
	AppID     int64
	GuildID   int64
	EmojiID   int64
	Data      []byte
	Tainted   bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type CacheGuild struct {
	AppID       int64
	GuildID     int64
	Data        []byte
	Unavailable bool
	Tainted     bool
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type CacheRole struct {
	AppID     int64
	GuildID   int64
	RoleID    int64
	Data      []byte
	Tainted   bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type CacheSticker struct {
	AppID     int64
	GuildID   int64
	StickerID int64
	Data      []byte
	Tainted   bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
