// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: roles.sql

package pgmodel

import (
	"context"
)

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM cache.roles WHERE app_id = $1 AND guild_id = $2 AND role_id = $3
`

type DeleteRoleParams struct {
	AppID   int64
	GuildID int64
	RoleID  int64
}

func (q *Queries) DeleteRole(ctx context.Context, arg DeleteRoleParams) error {
	_, err := q.db.Exec(ctx, deleteRole, arg.AppID, arg.GuildID, arg.RoleID)
	return err
}

const markShardRolesTainted = `-- name: MarkShardRolesTainted :exec
UPDATE cache.roles SET tainted = TRUE WHERE app_id = $1 AND guild_id % $2 = $3
`

type MarkShardRolesTaintedParams struct {
	AppID      int64
	ShardCount int64
	ShardID    int64
}

func (q *Queries) MarkShardRolesTainted(ctx context.Context, arg MarkShardRolesTaintedParams) error {
	_, err := q.db.Exec(ctx, markShardRolesTainted, arg.AppID, arg.ShardCount, arg.ShardID)
	return err
}
