// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: stickers.sql

package pgmodel

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSticker = `-- name: DeleteSticker :exec
DELETE FROM cache.stickers WHERE app_id = $1 AND guild_id = $2 AND sticker_id = $3
`

type DeleteStickerParams struct {
	AppID     int64
	GuildID   int64
	StickerID int64
}

func (q *Queries) DeleteSticker(ctx context.Context, arg DeleteStickerParams) error {
	_, err := q.db.Exec(ctx, deleteSticker, arg.AppID, arg.GuildID, arg.StickerID)
	return err
}

const getSticker = `-- name: GetSticker :one
SELECT app_id, guild_id, sticker_id, data, tainted, created_at, updated_at FROM cache.stickers WHERE app_id = $1 AND guild_id = $2 AND sticker_id = $3 LIMIT 1
`

type GetStickerParams struct {
	AppID     int64
	GuildID   int64
	StickerID int64
}

func (q *Queries) GetSticker(ctx context.Context, arg GetStickerParams) (CacheSticker, error) {
	row := q.db.QueryRow(ctx, getSticker, arg.AppID, arg.GuildID, arg.StickerID)
	var i CacheSticker
	err := row.Scan(
		&i.AppID,
		&i.GuildID,
		&i.StickerID,
		&i.Data,
		&i.Tainted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStickers = `-- name: GetStickers :many
SELECT app_id, guild_id, sticker_id, data, tainted, created_at, updated_at FROM cache.stickers WHERE app_id = $1 AND guild_id = $2 ORDER BY sticker_id LIMIT $4 OFFSET $3
`

type GetStickersParams struct {
	AppID   int64
	GuildID int64
	Offset  pgtype.Int4
	Limit   pgtype.Int4
}

func (q *Queries) GetStickers(ctx context.Context, arg GetStickersParams) ([]CacheSticker, error) {
	rows, err := q.db.Query(ctx, getStickers,
		arg.AppID,
		arg.GuildID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CacheSticker
	for rows.Next() {
		var i CacheSticker
		if err := rows.Scan(
			&i.AppID,
			&i.GuildID,
			&i.StickerID,
			&i.Data,
			&i.Tainted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markShardStickersTainted = `-- name: MarkShardStickersTainted :exec
UPDATE cache.stickers SET tainted = TRUE WHERE app_id = $1 AND guild_id % $2 = $3
`

type MarkShardStickersTaintedParams struct {
	AppID      int64
	ShardCount int64
	ShardID    int64
}

func (q *Queries) MarkShardStickersTainted(ctx context.Context, arg MarkShardStickersTaintedParams) error {
	_, err := q.db.Exec(ctx, markShardStickersTainted, arg.AppID, arg.ShardCount, arg.ShardID)
	return err
}

const searchStickers = `-- name: SearchStickers :many
SELECT app_id, guild_id, sticker_id, data, tainted, created_at, updated_at FROM cache.stickers WHERE app_id = $1 AND guild_id = $2 AND data @> $3 ORDER BY sticker_id LIMIT $5 OFFSET $4
`

type SearchStickersParams struct {
	AppID   int64
	GuildID int64
	Data    []byte
	Offset  pgtype.Int4
	Limit   pgtype.Int4
}

func (q *Queries) SearchStickers(ctx context.Context, arg SearchStickersParams) ([]CacheSticker, error) {
	rows, err := q.db.Query(ctx, searchStickers,
		arg.AppID,
		arg.GuildID,
		arg.Data,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CacheSticker
	for rows.Next() {
		var i CacheSticker
		if err := rows.Scan(
			&i.AppID,
			&i.GuildID,
			&i.StickerID,
			&i.Data,
			&i.Tainted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
