// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: apps.sql

package pgmodel

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApp = `-- name: CreateApp :one
INSERT INTO gateway.apps (
    id,
    group_id,
    display_name, 
    discord_client_id, 
    discord_bot_token, 
    discord_public_key, 
    discord_client_secret,
    shard_count,
    constraints,
    config,
    created_at, 
    updated_at
)
VALUES (
    $1, 
    $2, 
    $3, 
    $4, 
    $5, 
    $6, 
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
RETURNING id, group_id, display_name, discord_client_id, discord_bot_token, discord_public_key, discord_client_secret, shard_count, constraints, config, disabled, disabled_code, disabled_message, created_at, updated_at
`

type CreateAppParams struct {
	ID                  int64
	GroupID             string
	DisplayName         string
	DiscordClientID     int64
	DiscordBotToken     string
	DiscordPublicKey    string
	DiscordClientSecret pgtype.Text
	ShardCount          int32
	Constraints         []byte
	Config              []byte
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
}

func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) (GatewayApp, error) {
	row := q.db.QueryRow(ctx, createApp,
		arg.ID,
		arg.GroupID,
		arg.DisplayName,
		arg.DiscordClientID,
		arg.DiscordBotToken,
		arg.DiscordPublicKey,
		arg.DiscordClientSecret,
		arg.ShardCount,
		arg.Constraints,
		arg.Config,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i GatewayApp
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.DisplayName,
		&i.DiscordClientID,
		&i.DiscordBotToken,
		&i.DiscordPublicKey,
		&i.DiscordClientSecret,
		&i.ShardCount,
		&i.Constraints,
		&i.Config,
		&i.Disabled,
		&i.DisabledCode,
		&i.DisabledMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteApp = `-- name: DeleteApp :exec
DELETE FROM gateway.apps WHERE id = $1
`

func (q *Queries) DeleteApp(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteApp, id)
	return err
}

const disableApp = `-- name: DisableApp :one
UPDATE gateway.apps SET 
    disabled = TRUE,
    disabled_code = $2,
    disabled_message = $3,
    updated_at = $4
WHERE id = $1
RETURNING id, group_id, display_name, discord_client_id, discord_bot_token, discord_public_key, discord_client_secret, shard_count, constraints, config, disabled, disabled_code, disabled_message, created_at, updated_at
`

type DisableAppParams struct {
	ID              int64
	DisabledCode    pgtype.Text
	DisabledMessage pgtype.Text
	UpdatedAt       pgtype.Timestamp
}

func (q *Queries) DisableApp(ctx context.Context, arg DisableAppParams) (GatewayApp, error) {
	row := q.db.QueryRow(ctx, disableApp,
		arg.ID,
		arg.DisabledCode,
		arg.DisabledMessage,
		arg.UpdatedAt,
	)
	var i GatewayApp
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.DisplayName,
		&i.DiscordClientID,
		&i.DiscordBotToken,
		&i.DiscordPublicKey,
		&i.DiscordClientSecret,
		&i.ShardCount,
		&i.Constraints,
		&i.Config,
		&i.Disabled,
		&i.DisabledCode,
		&i.DisabledMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApp = `-- name: GetApp :one
SELECT id, group_id, display_name, discord_client_id, discord_bot_token, discord_public_key, discord_client_secret, shard_count, constraints, config, disabled, disabled_code, disabled_message, created_at, updated_at FROM gateway.apps WHERE id = $1 LIMIT 1
`

func (q *Queries) GetApp(ctx context.Context, id int64) (GatewayApp, error) {
	row := q.db.QueryRow(ctx, getApp, id)
	var i GatewayApp
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.DisplayName,
		&i.DiscordClientID,
		&i.DiscordBotToken,
		&i.DiscordPublicKey,
		&i.DiscordClientSecret,
		&i.ShardCount,
		&i.Constraints,
		&i.Config,
		&i.Disabled,
		&i.DisabledCode,
		&i.DisabledMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApps = `-- name: GetApps :many
SELECT id, group_id, display_name, discord_client_id, discord_bot_token, discord_public_key, discord_client_secret, shard_count, constraints, config, disabled, disabled_code, disabled_message, created_at, updated_at FROM gateway.apps
`

func (q *Queries) GetApps(ctx context.Context) ([]GatewayApp, error) {
	rows, err := q.db.Query(ctx, getApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GatewayApp
	for rows.Next() {
		var i GatewayApp
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.DisplayName,
			&i.DiscordClientID,
			&i.DiscordBotToken,
			&i.DiscordPublicKey,
			&i.DiscordClientSecret,
			&i.ShardCount,
			&i.Constraints,
			&i.Config,
			&i.Disabled,
			&i.DisabledCode,
			&i.DisabledMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnabledApps = `-- name: GetEnabledApps :many
SELECT id, group_id, display_name, discord_client_id, discord_bot_token, discord_public_key, discord_client_secret, shard_count, constraints, config, disabled, disabled_code, disabled_message, created_at, updated_at FROM gateway.apps WHERE disabled = FALSE AND (shard_count > 1 OR id % $1 = $2)
`

type GetEnabledAppsParams struct {
	GatewayCount int64
	GatewayID    int64
}

func (q *Queries) GetEnabledApps(ctx context.Context, arg GetEnabledAppsParams) ([]GatewayApp, error) {
	rows, err := q.db.Query(ctx, getEnabledApps, arg.GatewayCount, arg.GatewayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GatewayApp
	for rows.Next() {
		var i GatewayApp
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.DisplayName,
			&i.DiscordClientID,
			&i.DiscordBotToken,
			&i.DiscordPublicKey,
			&i.DiscordClientSecret,
			&i.ShardCount,
			&i.Constraints,
			&i.Config,
			&i.Disabled,
			&i.DisabledCode,
			&i.DisabledMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApp = `-- name: UpdateApp :one
UPDATE gateway.apps SET 
    group_id = $2,
    display_name = $3, 
    discord_client_id = $4, 
    discord_bot_token = $5, 
    discord_public_key = $6, 
    discord_client_secret = $7,
    shard_count = $8,
    constraints = $9,
    config = $10,
    disabled = $11,  
    disabled_code = $12,
    disabled_message = $13,
    updated_at = $14
WHERE id = $1
RETURNING id, group_id, display_name, discord_client_id, discord_bot_token, discord_public_key, discord_client_secret, shard_count, constraints, config, disabled, disabled_code, disabled_message, created_at, updated_at
`

type UpdateAppParams struct {
	ID                  int64
	GroupID             string
	DisplayName         string
	DiscordClientID     int64
	DiscordBotToken     string
	DiscordPublicKey    string
	DiscordClientSecret pgtype.Text
	ShardCount          int32
	Constraints         []byte
	Config              []byte
	Disabled            bool
	DisabledCode        pgtype.Text
	DisabledMessage     pgtype.Text
	UpdatedAt           pgtype.Timestamp
}

func (q *Queries) UpdateApp(ctx context.Context, arg UpdateAppParams) (GatewayApp, error) {
	row := q.db.QueryRow(ctx, updateApp,
		arg.ID,
		arg.GroupID,
		arg.DisplayName,
		arg.DiscordClientID,
		arg.DiscordBotToken,
		arg.DiscordPublicKey,
		arg.DiscordClientSecret,
		arg.ShardCount,
		arg.Constraints,
		arg.Config,
		arg.Disabled,
		arg.DisabledCode,
		arg.DisabledMessage,
		arg.UpdatedAt,
	)
	var i GatewayApp
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.DisplayName,
		&i.DiscordClientID,
		&i.DiscordBotToken,
		&i.DiscordPublicKey,
		&i.DiscordClientSecret,
		&i.ShardCount,
		&i.Constraints,
		&i.Config,
		&i.Disabled,
		&i.DisabledCode,
		&i.DisabledMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertApp = `-- name: UpsertApp :exec
INSERT INTO gateway.apps (
    id,
    group_id,
    display_name,
    discord_client_id,
    discord_bot_token,
    discord_public_key,
    discord_client_secret,
    shard_count,
    constraints,
    config,
    created_at,
    updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (id) DO UPDATE SET
    group_id = EXCLUDED.group_id,
    display_name = EXCLUDED.display_name,
    discord_client_id = EXCLUDED.discord_client_id,
    discord_bot_token = EXCLUDED.discord_bot_token,
    discord_public_key = EXCLUDED.discord_public_key,
    discord_client_secret = EXCLUDED.discord_client_secret,
    shard_count = EXCLUDED.shard_count,
    constraints = EXCLUDED.constraints,
    config = EXCLUDED.config,
    updated_at = EXCLUDED.updated_at,
    disabled = FALSE
`

type UpsertAppParams struct {
	ID                  int64
	GroupID             string
	DisplayName         string
	DiscordClientID     int64
	DiscordBotToken     string
	DiscordPublicKey    string
	DiscordClientSecret pgtype.Text
	ShardCount          int32
	Constraints         []byte
	Config              []byte
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
}

func (q *Queries) UpsertApp(ctx context.Context, arg UpsertAppParams) error {
	_, err := q.db.Exec(ctx, upsertApp,
		arg.ID,
		arg.GroupID,
		arg.DisplayName,
		arg.DiscordClientID,
		arg.DiscordBotToken,
		arg.DiscordPublicKey,
		arg.DiscordClientSecret,
		arg.ShardCount,
		arg.Constraints,
		arg.Config,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
