// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: apps.sql

package pgmodel

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApp = `-- name: CreateApp :one
INSERT INTO gateway.apps (
    id, 
    display_name, 
    discord_client_id, 
    discord_bot_token, 
    discord_public_key, 
    discord_client_secret,
    created_at, 
    updated_at
)
VALUES (
    $1, 
    $2, 
    $3, 
    $4, 
    $5, 
    $6, 
    $7,
    $8
)
RETURNING id, display_name, discord_client_id, discord_bot_token, discord_public_key, discord_client_secret, disabled, disabled_code, disabled_message, created_at, updated_at
`

type CreateAppParams struct {
	ID                  int64
	DisplayName         string
	DiscordClientID     int64
	DiscordBotToken     string
	DiscordPublicKey    string
	DiscordClientSecret pgtype.Text
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
}

func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) (GatewayApp, error) {
	row := q.db.QueryRow(ctx, createApp,
		arg.ID,
		arg.DisplayName,
		arg.DiscordClientID,
		arg.DiscordBotToken,
		arg.DiscordPublicKey,
		arg.DiscordClientSecret,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i GatewayApp
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.DiscordClientID,
		&i.DiscordBotToken,
		&i.DiscordPublicKey,
		&i.DiscordClientSecret,
		&i.Disabled,
		&i.DisabledCode,
		&i.DisabledMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteApp = `-- name: DeleteApp :exec
DELETE FROM gateway.apps WHERE id = $1
`

func (q *Queries) DeleteApp(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteApp, id)
	return err
}

const disableApp = `-- name: DisableApp :one
UPDATE gateway.apps SET 
    disabled = TRUE,
    disabled_code = $2,
    disabled_message = $3,
    updated_at = $4
WHERE id = $1
RETURNING id, display_name, discord_client_id, discord_bot_token, discord_public_key, discord_client_secret, disabled, disabled_code, disabled_message, created_at, updated_at
`

type DisableAppParams struct {
	ID              int64
	DisabledCode    pgtype.Text
	DisabledMessage pgtype.Text
	UpdatedAt       pgtype.Timestamp
}

func (q *Queries) DisableApp(ctx context.Context, arg DisableAppParams) (GatewayApp, error) {
	row := q.db.QueryRow(ctx, disableApp,
		arg.ID,
		arg.DisabledCode,
		arg.DisabledMessage,
		arg.UpdatedAt,
	)
	var i GatewayApp
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.DiscordClientID,
		&i.DiscordBotToken,
		&i.DiscordPublicKey,
		&i.DiscordClientSecret,
		&i.Disabled,
		&i.DisabledCode,
		&i.DisabledMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApp = `-- name: GetApp :one
SELECT id, display_name, discord_client_id, discord_bot_token, discord_public_key, discord_client_secret, disabled, disabled_code, disabled_message, created_at, updated_at FROM gateway.apps WHERE id = $1 LIMIT 1
`

func (q *Queries) GetApp(ctx context.Context, id int64) (GatewayApp, error) {
	row := q.db.QueryRow(ctx, getApp, id)
	var i GatewayApp
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.DiscordClientID,
		&i.DiscordBotToken,
		&i.DiscordPublicKey,
		&i.DiscordClientSecret,
		&i.Disabled,
		&i.DisabledCode,
		&i.DisabledMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApps = `-- name: GetApps :many
SELECT id, display_name, discord_client_id, discord_bot_token, discord_public_key, discord_client_secret, disabled, disabled_code, disabled_message, created_at, updated_at FROM gateway.apps
`

func (q *Queries) GetApps(ctx context.Context) ([]GatewayApp, error) {
	rows, err := q.db.Query(ctx, getApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GatewayApp
	for rows.Next() {
		var i GatewayApp
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.DiscordClientID,
			&i.DiscordBotToken,
			&i.DiscordPublicKey,
			&i.DiscordClientSecret,
			&i.Disabled,
			&i.DisabledCode,
			&i.DisabledMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnabledApps = `-- name: GetEnabledApps :many
SELECT id, display_name, discord_client_id, discord_bot_token, discord_public_key, discord_client_secret, disabled, disabled_code, disabled_message, created_at, updated_at FROM gateway.apps WHERE disabled = FALSE
`

func (q *Queries) GetEnabledApps(ctx context.Context) ([]GatewayApp, error) {
	rows, err := q.db.Query(ctx, getEnabledApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GatewayApp
	for rows.Next() {
		var i GatewayApp
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.DiscordClientID,
			&i.DiscordBotToken,
			&i.DiscordPublicKey,
			&i.DiscordClientSecret,
			&i.Disabled,
			&i.DisabledCode,
			&i.DisabledMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApp = `-- name: UpdateApp :one
UPDATE gateway.apps SET 
    display_name = $2, 
    discord_client_id = $3, 
    discord_bot_token = $4, 
    discord_public_key = $5, 
    discord_client_secret = $6,
    disabled = $7,
    disabled_code = $8,
    disabled_message = $9,
    updated_at = $10
WHERE id = $1
RETURNING id, display_name, discord_client_id, discord_bot_token, discord_public_key, discord_client_secret, disabled, disabled_code, disabled_message, created_at, updated_at
`

type UpdateAppParams struct {
	ID                  int64
	DisplayName         string
	DiscordClientID     int64
	DiscordBotToken     string
	DiscordPublicKey    string
	DiscordClientSecret pgtype.Text
	Disabled            bool
	DisabledCode        pgtype.Text
	DisabledMessage     pgtype.Text
	UpdatedAt           pgtype.Timestamp
}

func (q *Queries) UpdateApp(ctx context.Context, arg UpdateAppParams) (GatewayApp, error) {
	row := q.db.QueryRow(ctx, updateApp,
		arg.ID,
		arg.DisplayName,
		arg.DiscordClientID,
		arg.DiscordBotToken,
		arg.DiscordPublicKey,
		arg.DiscordClientSecret,
		arg.Disabled,
		arg.DisabledCode,
		arg.DisabledMessage,
		arg.UpdatedAt,
	)
	var i GatewayApp
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.DiscordClientID,
		&i.DiscordBotToken,
		&i.DiscordPublicKey,
		&i.DiscordClientSecret,
		&i.Disabled,
		&i.DisabledCode,
		&i.DisabledMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
