// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: groups.sql

package pgmodel

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO gateway.groups (id, display_name, created_at, updated_at) VALUES ($1, $2, $3, $4) RETURNING id, display_name, created_at, updated_at
`

type CreateGroupParams struct {
	ID          string
	DisplayName string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (GatewayGroup, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.ID,
		arg.DisplayName,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i GatewayGroup
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM gateway.groups WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteGroup, id)
	return err
}

const getGroup = `-- name: GetGroup :one
SELECT id, display_name, created_at, updated_at FROM gateway.groups WHERE id = $1 LIMIT 1
`

func (q *Queries) GetGroup(ctx context.Context, id string) (GatewayGroup, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i GatewayGroup
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroups = `-- name: GetGroups :many
SELECT id, display_name, created_at, updated_at FROM gateway.groups
`

func (q *Queries) GetGroups(ctx context.Context) ([]GatewayGroup, error) {
	rows, err := q.db.Query(ctx, getGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GatewayGroup
	for rows.Next() {
		var i GatewayGroup
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE gateway.groups SET display_name = $2, updated_at = $3 WHERE id = $1 RETURNING id, display_name, created_at, updated_at
`

type UpdateGroupParams struct {
	ID          string
	DisplayName string
	UpdatedAt   pgtype.Timestamp
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (GatewayGroup, error) {
	row := q.db.QueryRow(ctx, updateGroup, arg.ID, arg.DisplayName, arg.UpdatedAt)
	var i GatewayGroup
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
