// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: identify_limits.sql

package pgmodel

import (
	"context"
)

const tryLockBucket = `-- name: TryLockBucket :one
SELECT pg_try_advisory_xact_lock($1, $2)
`

type TryLockBucketParams struct {
	PgTryAdvisoryXactLock   int32
	PgTryAdvisoryXactLock_2 int32
}

func (q *Queries) TryLockBucket(ctx context.Context, arg TryLockBucketParams) (bool, error) {
	row := q.db.QueryRow(ctx, tryLockBucket, arg.PgTryAdvisoryXactLock, arg.PgTryAdvisoryXactLock_2)
	var pg_try_advisory_xact_lock bool
	err := row.Scan(&pg_try_advisory_xact_lock)
	return pg_try_advisory_xact_lock, err
}
