// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package pgmodel

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GatewayApp struct {
	ID                  int64
	GroupID             string
	DisplayName         string
	DiscordClientID     int64
	DiscordBotToken     string
	DiscordPublicKey    string
	DiscordClientSecret pgtype.Text
	ShardCount          int32
	Constraints         []byte
	Config              []byte
	Disabled            bool
	DisabledCode        pgtype.Text
	DisabledMessage     pgtype.Text
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
}

type GatewayGroup struct {
	ID                 string
	DisplayName        string
	DefaultConfig      []byte
	DefaultConstraints []byte
	CreatedAt          pgtype.Timestamp
	UpdatedAt          pgtype.Timestamp
}

type GatewayShardSession struct {
	ID            string
	AppID         int64
	ShardID       int32
	ShardCount    int32
	LastSequence  int32
	ResumeUrl     string
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	InvalidatedAt pgtype.Timestamp
}
