// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package pgmodel

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GatewayApp struct {
	ID                  int64
	DisplayName         string
	DiscordClientID     int64
	DiscordBotToken     string
	DiscordPublicKey    string
	DiscordClientSecret pgtype.Text
	Disabled            bool
	DisabledCode        pgtype.Text
	DisabledMessage     pgtype.Text
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
}
