// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: shard_sessions.sql

package pgmodel

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLastShardSession = `-- name: GetLastShardSession :one
SELECT id, app_id, shard_id, last_sequence, resume_url, created_at, updated_at, invalidated_at FROM gateway.shard_sessions WHERE app_id = $1 AND shard_id = $2 ORDER BY updated_at DESC LIMIT 1
`

type GetLastShardSessionParams struct {
	AppID   int64
	ShardID int32
}

func (q *Queries) GetLastShardSession(ctx context.Context, arg GetLastShardSessionParams) (GatewayShardSession, error) {
	row := q.db.QueryRow(ctx, getLastShardSession, arg.AppID, arg.ShardID)
	var i GatewayShardSession
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.ShardID,
		&i.LastSequence,
		&i.ResumeUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InvalidatedAt,
	)
	return i, err
}

const invalidateShardSession = `-- name: InvalidateShardSession :exec
UPDATE gateway.shard_sessions SET invalidated_at = $3 WHERE app_id = $1 AND shard_id = $2
`

type InvalidateShardSessionParams struct {
	AppID         int64
	ShardID       int32
	InvalidatedAt pgtype.Timestamp
}

func (q *Queries) InvalidateShardSession(ctx context.Context, arg InvalidateShardSessionParams) error {
	_, err := q.db.Exec(ctx, invalidateShardSession, arg.AppID, arg.ShardID, arg.InvalidatedAt)
	return err
}

const purgeSessions = `-- name: PurgeSessions :exec
DELETE FROM gateway.shard_sessions
`

func (q *Queries) PurgeSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, purgeSessions)
	return err
}

const upsertShardSession = `-- name: UpsertShardSession :exec
INSERT INTO gateway.shard_sessions (
    id,
    app_id,
    shard_id,
    last_sequence,
    resume_url,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO UPDATE SET
    last_sequence = EXCLUDED.last_sequence,
    resume_url = EXCLUDED.resume_url,
    updated_at = EXCLUDED.updated_at
`

type UpsertShardSessionParams struct {
	ID           string
	AppID        int64
	ShardID      int32
	LastSequence int32
	ResumeUrl    string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

func (q *Queries) UpsertShardSession(ctx context.Context, arg UpsertShardSessionParams) error {
	_, err := q.db.Exec(ctx, upsertShardSession,
		arg.ID,
		arg.AppID,
		arg.ShardID,
		arg.LastSequence,
		arg.ResumeUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
